import {
  AlignLeft,
  Calendar,
  CircleDot,
  Clock,
  Hash,
  Heading1,
  Link2,
  Mail,
  Minus,
  Phone,
  SlidersHorizontal,
  SquareCheck,
  SquareCheckBig,
  Star,
  Text,
  Type,
  List,
  ListChecks,
  type LucideIcon,
} from "lucide-react";
import type { FieldType } from "@/lib/types";

export const FIELD_ICONS: Record<FieldType, LucideIcon> = {
  text: Type,
  textarea: AlignLeft,
  email: Mail,
  phone: Phone,
  number: Hash,
  url: Link2,
  date: Calendar,
  time: Clock,
  select: List,
  multiselect: ListChecks,
  radio: CircleDot,
  checkboxGroup: SquareCheckBig,
  checkbox: SquareCheck,
  rating: Star,
  range: SlidersHorizontal,
  heading: Heading1,
  paragraph: Text,
  divider: Minus,
};
